server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true

logging:
  config: classpath:logback.xml
  level:
    com.alibaba.nacos: info
    root: info

spring:
  main:
    allow-circular-references: true

binance:
  wsstream:
    addr: "wss://data-stream.binance.vision/ws"