server:
  port: 8080
spring:
  servlet:
    multipart:
      location: /Users/autech/upload_tmp
      max-file-size: 20MB
      max-request-size: 22MB
  main:
    allow-circular-references: true
  cloud:
    openfeign:
      httpclient:
        connection-timeout: 20000
      client:
        config:
          default:
            connect-timeout: 20000
            read-timeout: 8000

logging:
  config: classpath:logback.xml
  level:
    root: info

#wallet:
#  path: wallet
#  suffix: .unk