server:
  port: 8080
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: false
    openfeign:
      httpclient:
        connection-timeout: 20000
      client:
        config:
          default:
            connect-timeout: 20000
            read-timeout: 8000
  main:
    allow-circular-references: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

